name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email rajesh.amby521@gmail.com 
          # git config --global user.name rajesh 
          git config --global user.email rajesh.amby521@gmail.com
          git config --global user.name rajesh
          git status
          # change this remote url for examle your remote url is https://github.com/rajeshamby521/way2fitlite.github.io.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/rajeshamby521/way2fitlite.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
